#ifndef CONSTANTS_H
#define CONSTANTS_H

#define LENGTH_BYTES 2
#define ID_BYTES 2
#define COUNTDOWN_BYTES 2
#define AMOUNT_BYTES 4
#define FRAME_BYTES 4
#define TIME_BYTES 4
#define CODE_BYTES 1
#define AMOUNT_PLAYERS_BYTES 1
#define BOOL_BYTES 1
#define MAP_NUMBER_BYTES 1
#define CAR_STATE_BYTES                                                        \
    (ID_BYTES + 4 * AMOUNT_BYTES + 3 * LENGTH_BYTES + CHECKPOINT_ARROW_BYTES + \
     CHECKPOINT_INFO_BYTES + 4 * BOOL_BYTES)
#define NPC_STATE_BYTES (3 * AMOUNT_BYTES + LENGTH_BYTES + BOOL_BYTES)
#define CHECKPOINT_INFO_BYTES (ID_BYTES + 4 * AMOUNT_BYTES + CODE_BYTES)
#define CHECKPOINT_ARROW_BYTES (3 * AMOUNT_BYTES)
#define LOBBY_BYTES (CODE_BYTES + ID_BYTES + 2 * AMOUNT_PLAYERS_BYTES)
#define CAR_PROPERTIES_BYTES (1 + 5 * LENGTH_BYTES)
#define PLAYER_STATE_BYTES \
    (ID_BYTES + BOOL_BYTES + AMOUNT_PLAYERS_BYTES + 2 * TIME_BYTES + CAR_PROPERTIES_BYTES)

#define MAX_PLAYERS_RACE 2


#define ACT_ACCEL_PRESS 0x01
#define ACT_ACCEL_RELEASE 0x02
#define ACT_BRAKE_PRESS 0x03
#define ACT_BRAKE_RELEASE 0x04
#define ACT_LEFT_PRESS 0x05
#define ACT_LEFT_RELEASE 0x06
#define ACT_RIGHT_PRESS 0x07
#define ACT_RIGHT_RELEASE 0x08
#define ACT_NITRO_PRESS 0x09
#define ACT_NITRO_RELEASE 0x0A
#define ACT_EXIT 0x0B

#define ACT_IMPROVE_SPEED 0x0C
#define ACT_IMPROVE_ACCELERATION 0x0D
#define ACT_IMPROVE_HEALTH 0x0E
#define ACT_IMPROVE_MASS 0x0F
#define ACT_IMPROVE_HANDLING 0x10

#define START_GAME 0x0B
#define END_GAME 0x0C

#define COMMON_CHECKPOINT 1
#define SPECIAL_CHECKPOINT 2

#define COUNTDOWN_TIME 10         // segundos

#define UPDATE_STATE 0x0D

#endif
