#ifndef CONSTANTS_H
#define CONSTANTS_H

#define LENGTH_BYTES 2
#define ID_BYTES 2
#define AMOUNT_BYTES 4
#define FRAME_BYTES 4
#define CODE_BYTES 1
#define AMOUNT_PLAYERS_BYTES 1
#define CAR_STATE_BYTES (ID_BYTES + 4 * AMOUNT_BYTES + LENGTH_BYTES)

#define MAX_PLAYERS_RACE 2


#define ACT_ACCEL_PRESS 0x01
#define ACT_ACCEL_RELEASE 0x02
#define ACT_BRAKE_PRESS 0x03
#define ACT_BRAKE_RELEASE 0x04
#define ACT_LEFT_PRESS 0x05
#define ACT_LEFT_RELEASE 0x06
#define ACT_RIGHT_PRESS 0x07
#define ACT_RIGHT_RELEASE 0x08
#define ACT_NITRO_PRESS 0x09
#define ACT_NITRO_RELEASE 0x0A
#define ACT_EXIT 0x0B

#define START_GAME 0x0B
#define END_GAME 0x0C

#define UPDATE_STATE 0x0D

#endif
